export { PrismaClient } from "@prisma/client";
export type {
  Profile,
  Clinic,
  ClinicAdmin,
  Professional,
  Insurance,
  Patient,
  Service,
  ScheduleConfig,
  WorkingHour,
  ScheduleBlock,
  Appointment,
  ClinicalRecord,
  ClinicalRecordAudit,
  SessionNote,
  BillingItem,
  Coupon,
  LineOfBusiness,
  UserRole,
  AppointmentStatus,
  SubscriptionPlan,
  SubscriptionStatus,
} from "@prisma/client";
